{{- with include "farm.oidcProviders" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "farm.fullname" $ }}-oidc
  labels: {{- include "farm.labels" $ | nindent 4 }}
stringData:
  oidc.json: {{ . | quote }}
{{- end }}
